include: /build/gitlab-ci.yml

variables:
  PROJECT_PATH: "sosy-lab/software/java-common-lib"
  GH_REF: "github.com/sosy-lab/java-common-lib"
  # Version of https://gitlab.com/sosy-lab/software/refaster/ to use
  REFASTER_REPO_REVISION: 152e50177ad80cee6e919809958dc3858f72fa3e
  # Needs to be synchronized with Error Prone version in lib/ivy.xml
  REFASTER_VERSION: 2.3.3

build:jdk-13:
  variables:
    # https://github.com/google/error-prone/issues/1106
    ANT_PROPS_BUILD: "-Divy.disable=true -Derrorprone.disable=true"
