# This file is part of SoSy-Lab Common,
# a library of useful utilities:
# https://github.com/sosy-lab/java-common-lib
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

include: /build/gitlab-ci.yml

variables:
  PROJECT_PATH: "sosy-lab/software/java-common-lib"
  GH_REF: "github.com/sosy-lab/java-common-lib"
  # Version of https://gitlab.com/sosy-lab/software/refaster/ to use
  REFASTER_REPO_REVISION: cfc87fc424f3a3d0d3a8e3637bab6970a17f1ae9
  # Needs to be synchronized with Error Prone version in lib/ivy.xml
  REFASTER_VERSION: 2.3.4

build:jdk-14:
  variables:
    # https://github.com/google/error-prone/issues/1106
    ANT_PROPS_BUILD: "-Divy.disable=true -Derrorprone.disable=true"
