language: java
jdk:
  - openjdk7
  - oraclejdk8
env:
  global:
    - GH_REF: github.com/dbeyer/common-java.git
install:
  - ant resolve-dependencies
script:
  - ant unit-tests
  - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
  - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
  - ant javadoc
deploy:
  skip_cleanup: true
  provider: script
  script: build/deploy-gh-pages.sh
  on:
    jdk: openjdk7
notifications:
  email:
    - common-java-dev@groups.google.com
cache:
  directories:
  - $HOME/.ivy2
