language: java
install:
  - ant resolve-dependencies
script:
  - ant tests
  - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
notifications:
  email:
    - Common-Lib@sosy-lab.org
cache:
  directories:
  - $HOME/.ivy2
