language: java
install:
  - ant resolve-dependencies
script:
  - ant unit-tests
  - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
  - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
notifications:
  email:
    - Common-Lib@sosy-lab.org
cache:
  directories:
  - $HOME/.ivy2
